---
- name: OS specific config 
  include_tasks: "{{ ansible_distribution | lower }}.yaml"
  tags: os 
  
- name: Common config 
  include_tasks: common.yaml 

- name: Establish k3s version 
  include_tasks: k3s_version.yaml 

- name: Install k3s
  include_tasks: k3s_install.yaml 

- name: Trigger rolling restart (if an upgrade)
  include_tasks: k3s_restart.yaml 
  when: k3s_upgrade | bool